### ISSUE TITLE
Expired Authentication Token Error

### ISSUE THREAD

**Issue by Kaijisse** [ctesta-oneillmsft/asa-vtd#7]
Hi, 
Getting the following error message when deploying the setup script:
Invoke-RestMethod : {"code":"ExpiredAuthenticationToken","message":"Token Authentication failed with SecurityTokenExpiredException - IDX10223: Lifetime validation failed. The token is expired. ValidTo: '[PII is hidden]', Current time:
'[PII is hidden]'."}

**Comment by joelhulen** [comment]
This issue should now be resolved. Please try again with the script changes. Also, please be sure to carefully follow all steps.

**Comment by yogiazaad** [comment]
Hello I still see this error.

Invoke-RestMethod: {"code":"ExpiredAuthenticationToken","message":"Token Authentication failed with SecurityTokenExpiredException - IDX10223:
Lifetime validation failed. The token is expired. ValidTo: '1/14/2023 11:04:28 PM', Current time: '1/14/2023 11:09:37 PM'."}Deleting pipeline Setup - Load SQL Pool (global)
Web request status [Web request completed. (Number of bytes processed: 12912078)                                     ]
Deleting dataset wwi02_product_adls
